### ISSUE TITLE
Add succes when 404 not found occurs. 

### ISSUE THREAD

**Issue by mvandongen90** [Tools4everBV/HelloID-Conn-Prov-Target-Raet-Beaufort-IAM-API-Contact-Details#10]
If a person is deleted in BO4 and the delete action for Contact Details runs this results in a error 404 not found. 
Is it possible or desired that the 404 not found turns into a succes then a delete action takes place?

**Comment by rhouthuijzen** [comment]
@mvandongen90  thank you for your feedback.

For some reason this is only implemented in the update script. I will add it in the delete script for PSv2. This should be fixed with:

``` Powershell
        if ($errorMessage.AuditErrorMessage -Like "*Not Found*" -or $errorMessage.AuditErrorMessage -Like "No employee found in Raet Beaufort with $($correlationProperty) '$($correlationValue)'") {
            write-verbose "No employee found in Raet Beaufort with personCode [$($actionContext.References.Account)]. Possibly already deleted."
            $correlatedAccount = $null
        }
```

If not we should try:

``` Powershell
        if ($_.Exception.Response.StatusCode -eq 400) {
            $responseUser = $null
        }
```
