### ISSUE TITLE
Account correlation field is mandatory when enabling correlation in the target system

### ISSUE THREAD

**Issue by mouki9** [Tools4everBV/HelloID-Conn-Prov-Target-Raet-Beaufort-IAM-API-Contact-Details#12]
As per title, whenever enabling correlation in the target system, an account correlation field must always be supplied. Make sure a field with mapping none is selected. In the powershell code we see only the person field is used for the correlation in the target. This will ensure the enabling of the correlation function is saved successfully.

**Comment by rhouthuijzen** [comment]
Fixed in new pull request
