### ISSUE TITLE
update event, compare object is incorrect

### ISSUE THREAD

**Issue by mouki9** [Tools4everBV/HelloID-Conn-Prov-Target-Raet-Beaufort-IAM-API-Contact-Details#13]
On line 253, the previous and new account object are compared:

            $splatCompareProperties = @{
                ReferenceObject  = $previousAccount.PSObject.Properties
                DifferenceObject = $account
            }

It should be:

            $splatCompareProperties = @{
                ReferenceObject  = $previousAccount.PSObject.Properties
                DifferenceObject = $account.PSObject.Properties
            }

**Comment by rhouthuijzen** [comment]
Fixed in new pull request
